apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: registry/opus-books-api
    jibMaven: {}
deploy:
  helm:
    releases:
    - name: books-api
      chartPath: ../charts/books-api
      setValues:
        auth.htpassword: dXNlcjE6JGFwcjEkcHFTb3VWTE4kQ2EvQVNKSFhLU2dJSlpsd295andtMQ==
        ingress.enabled: false
        h2.enabled: false
        image.repository: registry/opus-books-api
        service.type: NodePort
      setValueTemplates:
        image.tag: "{{.DIGEST}}"