apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: registry.k8.wildwidewest.xyz/repository/docker-repository/opus/books-api
    jibMaven: {}
deploy:
  helm:
    releases:
    - name: books-api-int
      chartPath: ../charts/books-api
      setValueTemplates:
        image.tag: "{{.DIGEST}}"
      overrides:
        auth:
          htpassword: dXNlcjE6JGFwcjEkcHFTb3VWTE4kQ2EvQVNKSFhLU2dJSlpsd295andtMQ==
        h2:
          enabled: true
        ingress:
          secretName: books-api-int-secret
          hosts:
            - books-api-int.k8.wildwidewest.xyz
          tls:
          - hosts:
              - books-api-int.k8.wildwidewest.xyz
            secretName: books-api-int-secret
          annotations:
            nginx.ingress.kubernetes.io/auth-secret: books-api-int-basicauthsecret
