apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: elkouhen/books-api
    jibMaven: {}
deploy:
  helm:
    releases:
    - name: books-api-dev
      chartPath: ../app-charts/books-api
      overrides:
        auth:
          enabled: false
        h2:
          enabled: false
        ingress:
          enabled: false
        service.type: LoadBalancer