apiVersion: v1
kind: Service
metadata:
  labels:
    app: books-api
  name: books-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: books-api
  type: LoadBalancer
