apiVersion: v1
kind: Service
metadata:
  labels:
    run: books-api
  name: books-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: books-api
  type: LoadBalancer