DROP TABLE IF EXISTS T_BOOK;

CREATE TABLE T_BOOK (
  BOK_ID  INTEGER      NOT NULL PRIMARY KEY,
  BOK_TITLE    VARCHAR(128) NOT NULL
);


INSERT INTO T_BOOK (BOK_ID, BOK_TITLE) VALUES (1, 'Design Pattern');

INSERT INTO T_BOOK (BOK_ID, BOK_TITLE) VALUES (2, 'Effective Java');